variable "api_gateway_vpc_endpoint_ids" {}
variable "api_gateway_configuration" {}
variable "env" {}
variable "acm_certificate_arn" {}
variable "domain_name" {}
variable "route53_zone_id" {}
variable "authorization_config" {}
variable "application" {}
variable "swagger_uri" {}
