variable "env" {}
variable "application" {}
variable "project" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "container_port" {}
variable "subnet_ip_block" {}
variable "protocol" {}
variable "app_count" {}
variable "fargate_cpu" {}
variable "fargate_memory" {}
variable "load_balancer" {}
variable "ecr_image" {}
variable "fargate_version" {}
variable "region" {}
variable "alb_listener_port" {}
variable "acm_arn" {}
variable "project_zone" {}
variable "cluster_id" {}
variable "min_capacity" {}
variable "max_capacity" {}
variable "host_header" {}
variable "service_health_check_path" {}
variable "aws_log_group_retention_in_days" {}
variable "ecs_logs" {}
